### ISSUE TITLE
Adding input format of type "subtitle"

### ISSUE THREAD

**Issue by braincoded** [pietrop/subtitlesComposer-app#2]
Could you please consider to add files of type "subtitles" as an input option?

https://www.readbeyond.it/aeneas/docs/clitutorial.html#input-text-formats
https://www.readbeyond.it/aeneas/docs/textfile.html#aeneas.textfile.TextFileFormat.SUBTITLES

Thanks a lot!

**Comment by pietrop** [comment]
Thanks for your question @braincoded
 
Could you tell me a bit more about the thinking behind this request?

The app uses this module to handle the alignment [`subtitlesComposer`](https://github.com/pietrop/subtitlesComposer).

Grand part of the modules does a pre-segmentation prep to create a file in that Aeneas subtitles format before calling aeneas.

See [here for more details on the pre-segmentation steps involved in creating that Aeneas subtitle file programmatically before calling aeneas](https://github.com/pietrop/subtitlesComposer/blob/master/steps.md)

The thinking is that if we can get the presegmentaion as good as possible there might be close to no need to manually edit the captions once Aeneas has done with the alignment (?).

In the meanwhile I am however due to popular demand consodering adding an optional manual intermediate step to the GUI for the users to to review the pre-segmented text before calling aeneas.

Looking forward to hear your thoughts.

**Comment by braincoded** [comment]
Sure.

While the automated text segmentation works quite well, the descision where to begin a new subtitle is often far away from the segmentation points which subtitlers would choose manually.
Simplified one could probably say that an automated segmentation prioritizes filling the lines to a maximum (which comes at the price of odd line/subtitle breaks) while manually edited subtitles focus more on a context driven segmentation. This often leads to have one line subtitles once in a while, which doesn't happen in the automated workflow.

The reason why I've asked for the input type "subtitles" is, that I find myself often in the situation that there are subtitle ready texts available. For such a scenario I miss the option to bypass the automated segmentation and do the alignment right away. An intermediate step to have the possibility to edit the auto segmented text before the alignment process would help, however, being able to provide a segmented text to begin with would be preferable.

**Comment by pietrop** [comment]
Ok, cool, closing this issue, unless you have any more questions, ideally I'd like to focus on tweaking the [auto pre-align steps, see here](https://github.com/pietrop/subtitlesComposer/blob/master/steps.md)

**Comment by pietrop** [comment]
I added an intermedia step in this test release 
https://github.com/pietrop/subtitlesComposer-app/releases/tag/1.0.7

see release notes and screenshots for more info

This is in order to do further user testing to improve and refine the pre-segmentation rules by exposing the current output of the segmentation algorithm to the users before  sending that off to Aeneas.
